// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-DgbyyHUnqnLtnKKUkFQ7BHuC3YcmWTA',
    appId: '1:686586767967:android:35c12ef2d1738d5bf349ea',
    messagingSenderId: '686586767967',
    projectId: 'assignmnetapptechnilfiy',
    databaseURL: 'https://assignmnetapptechnilfiy-default-rtdb.firebaseio.com',
    storageBucket: 'assignmnetapptechnilfiy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCcTycK4Kp7AQBxIPp8ATD6UCrTYO8dSw',
    appId: '1:686586767967:ios:ff9c8fe1fa6eb4f2f349ea',
    messagingSenderId: '686586767967',
    projectId: 'assignmnetapptechnilfiy',
    databaseURL: 'https://assignmnetapptechnilfiy-default-rtdb.firebaseio.com',
    storageBucket: 'assignmnetapptechnilfiy.appspot.com',
    iosBundleId: 'com.example.flutterApplicationAssignmnettechnilify',
  );
}
